# Project: 118A
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 118A.o
LINKOBJ  = 118A.o
LIBS     = -L"D:/programs/Dev-Cpp/MinGW64/lib" -L"D:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/programs/Dev-Cpp/MinGW64/include" -I"D:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/programs/Dev-Cpp/MinGW64/include" -I"D:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 118A.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

118A.o: 118A.cpp
	$(CPP) -c 118A.cpp -o 118A.o $(CXXFLAGS)
